# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 900eee3509f0bde057cd1c3ad9084332c5f15418f57529dda61aa2fdcd53ca1677483e76e314be5f2ad8060acf77a0f97a7e148db238269f961fac30e1f87dcd

test:
  secret_key_base: 9c044e1cdf5924b8a727148cbbc5135255df4bc3bb7494bfe2208d298d0fa342daf1cc447253bebe472b0df44dfbf1f7b709979deff9bc36bfc6a59f234eb4c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
